language: generic

sudo: true

os:
- linux

before_script:
- export CHROOTDIR=$TRAVIS_BUILD_DIR/chroot
- export CACHEDIR=$HOME/cache
- sudo -E chmod a+x $TRAVIS_BUILD_DIR/scripts/setup.sh && sudo -E $TRAVIS_BUILD_DIR/scripts/setup.sh

jobs:
  include:
  - stage: fetch source
    script:
    - sudo -E chmod a+x $TRAVIS_BUILD_DIR/scripts/fetch_source.sh && sudo -E $TRAVIS_BUILD_DIR/scripts/fetch_source.sh
  - stage: compile u-boot
    script:
    - sudo -E chmod a+x $TRAVIS_BUILD_DIR/scripts/build_uboot.sh && sudo -E $TRAVIS_BUILD_DIR/scripts/build_uboot.sh
  - stage: compile kernel
    script:
    - sudo -E chmod a+x $TRAVIS_BUILD_DIR/scripts/build_kernel.sh && sudo -E $TRAVIS_BUILD_DIR/scripts/build_kernel.sh
  - stage: compile other
    script:
    - export REV=$(git rev-parse HEAD | cut -c 1-8)
    - export KERNELVERSION=`sudo -E cat ${CACHEDIR}/output/kernel/kernelversion`
    - sudo -E chmod a+x $CHROOTDIR/build/scripts/build.sh && sudo -E $CHROOTDIR/build/scripts/build.sh
    - sudo -E mv $CACHEDIR/output/alpine-rpi-*.tar.xz ${HOME}/
    - sudo -E chmod a+x $TRAVIS_BUILD_DIR/scripts/cleanup.sh && sudo -E $TRAVIS_BUILD_DIR/scripts/cleanup.sh
    - export TAG=$ALPINE_VERSION-kernel-$KERNELVERSION-$REV
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ] &&
        [ "${TRAVIS_BRANCH}" = "master" ] &&
        [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
        [ -z "$(git tag -l ${TAG})" ]; then
        git tag ${TAG}
        git push --quiet "https://${GITHUB_TOKEN}@github.com/chalharu/alpine-rpi-aarch64.git" ${TAG} >/dev/null 2>&1
      fi
    deploy:
      skip_cleanup: true
      provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: ${HOME}/alpine-rpi-*.tar.xz
      on:
        tags: true

cache:
  apt: true
  directories:
    - $HOME/cache

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - ALPINE_VERSION=3.7.0
  - secure: H7zpAEum3F8g3I4IVGKI45TfhQsnZNABJPsfsm9KZjuOdlpzuwalT74RWc55n1P7sCKvOy0ZvliN6ZGW7uRZSbVnFhpxpmUiV9B9fEUaS1VVYnGpgcYPCWSiG3DvKedsxGroHF8mzEbmrW4AMkuFcg64xDg6r5GnbRxtDmr78iKntx9Zc0CBDIaN3LotXgp5B6/K35db+mJ/dwtpGMw9sHNGvdYDtAxZko3Wc6dYxVQfy8jf6+SnuWk2Ua4LAkDA0gomihPBYQwEvYgR3l9YlRfYU6lnq390BFxRcNl2LfXMcTd48AqPF14Qs+AtgJBi0KrPZBYwJC115kVZVYhjCWWNvV2PynjHbxHaeMkC3eEMf1MjKTJzrLxPkvFtbLmJvD2iGSJ58PvQgjgpAqjbhC+m6Ck8y56mbFdrHjHDKv1q0bnUgz9jR7CUX3L4Ghm6zpJa9MkJFaLe8VwJKdC0Bk3oqkMAhqwk/eYmNK5AZTAcmYJ6pg56oF9MmjOwZgGwkoFATvbU0rHqjN2nPFKG9pmKHPRNSa102P4Z6XRX6/MRQ/Iz4Ca4IXP/8QY/MVu15ubsklz6Vcf/t+rwUCV63KN6dygdryA6TARKptMY0VukquEjOQpMhPDCDraS6X+Hl04Itbvjtho9zbIo3LUwCHEHWVWBXwo9kVcLrML+eAw=
